language: python
python:
- '2.7'
virtualenv:
  system_site_packages: false
before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- REPO=`pwd`
- echo $REPO
- echo $TRAVIS_TAG
- pwd
- sudo apt-get -qq update
- sudo apt-get -qq install python2.7 python-pip git unzip
- sudo apt-get -qq install python-dev libevent-dev libsmi2ldbl snmp-mibs-downloader
- sudo apt-get install libxml2 libxml2-dev libxml2-utils libmysqlclient-dev
install:
- export PYTHONIOENCODING=UTF8
- python setup.py install
- git show HEAD:conpot/__init__.py > docs/source/conpot_version.py
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS conpot_unittest;'
script:
- nosetests -v
- sudo -E /home/travis/virtualenv/python2.7.8/bin/conpot -t conpot/tests/empty_template.xml
- xmllint --schema conpot/template.xsd conpot/templates/*.xml
notifications:
  irc:
  - irc.freenode.org#conpot-dev
deploy:
  provider: pypi
  user: Johnny.Vestergaard
  password:
    secure: SQ5TTqSe4FDEuCxnhnyURJ6jKVjwc76GCRCgTF6Md0EUNUdZmnxUqdVPC2IcwnNqA5JGUWmn8l+Fy+n/0vs2T/ZtyG1fDOHjiZSWHnwkiHWYCBg616lsI3LO6npDjpsO/vEzzRepgzPKLNjbQoUepv9ZtuOLUZwl/Uz6FidhEKQ=
  on:
    repo: glastopf/conpot
    all_branches: true
    condition: $TRAVIS_TAG =~ ^Release_[0-9]+[.][0-9]+[.][0-9]+
