language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: false
before_install:
 - REPO=`pwd`
 - echo $REPO
 - pwd
 - "sudo apt-get -qq update"
 - "sudo apt-get -qq install python2.7 python-pip git unzip"
 - "sudo apt-get -qq install python-dev libevent-dev libsmi2ldbl snmp-mibs-downloader"
 - "sudo apt-get install libxml2 libxml2-dev"
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - sudo {envpython} setup.py install
 - git show HEAD:conpot/__init__.py > docs/source/conpot_version.py
# command to run tests
script:
 - nosetests -v
 - sudo conpot -t conpot/tests/empty_template.xml
notifications:
 irc:
  - "irc.freenode.org#conpot-dev"
