language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - REPO=`pwd`
 - echo $REPO
 - pwd
 - "sudo apt-get -qq update"
 - "sudo apt-get -qq install python2.7 python-pip git unzip"
 - "sudo apt-get -qq install python-dev libevent-dev"
 - cd /tmp
 - git clone git://github.com/rep/hpfeeds.git hpfeeds
 - cd hpfeeds
 - sudo python setup.py install
 - cd /tmp
 - wget https://modbus-tk.googlecode.com/files/modbus-tk-0.4.2.zip
 - unzip modbus-tk-0.4.2.zip -d modbus_tk
 - cd modbus_tk
 - sudo python setup.py install
install:
 - export PYTHONIOENCODING=UTF8 # just in case
 - pwd
 - cd $REPO
 - pip install -r requirements.txt --use-mirrors
# command to run tests
script:
 - echo $REPO
 - pwd
 - cp config.py.dist config.py
 - sudo nosetests
notifications:
 irc:
  - "irc.freenode.org#glastopf"
